# Generated by Django 3.0.8 on 2020-08-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(blank=True, max_length=30, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cep',
            field=models.CharField(blank=True, max_length=8, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(blank=True, max_length=30, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='complemento',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(blank=True, max_length=50, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero',
            field=models.CharField(blank=True, max_length=5, verbose_name='Número'),
        ),
    ]
